function m = immoment_hu(I, n);
% function m = immoment_hu(I, n);
% 
%   I image nin Hu n. momentini hesaplar

[a, b] = CentreOfMass(I);

switch n
    case 1,
        m = (CentralisedMoment(I,2,0,a,b) +  ...
             CentralisedMoment(I,0,2,a,b)) / ...
             (Moment(I,0,0)^2);
    case 2,
        m = ((CentralisedMoment(I,2,0,a,b) -            ...
              CentralisedMoment(I,0,2,a,b))^2 +         ...
             (4 * CentralisedMoment(I,1,1,a,b))^2) /   ...
             (Moment(I,0,0)^2);
    case 8,
        m = ((CentralisedMoment(I,2,0,a,b) *            ...
              CentralisedMoment(I,0,2,a,b))^2 -         ...
             (CentralisedMoment(I,1,1,a,b))^2) /        ...
             (Moment(I,0,0)^4);
end
